"""Add project head workflow

Revision ID: 40a4a2dde4a6
Revises: 497b0df7196b
Create Date: 2026-06-20 16:48:42.455320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a4a2dde4a6'
down_revision = '497b0df7196b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('task_assignments_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['member_id'], ['user_id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_head_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['project_head_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_head_id')

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_assignments_user_id_fkey'), 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
