"""Add user roles

Revision ID: 497b0df7196b
Revises: b662679bd1de
Create Date: 2026-06-19 13:29:53.190269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497b0df7196b'
down_revision = 'b662679bd1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False,server_default='member'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
